module.exports = {
  tripAdvisorApiKey: "",
  bookingAffiliateId: "",
  bookingToken: "",
  bookingUseSandbox: false,
  bookingAccommodationIds: {},
  yelpApiKey: "",
  yelpFusionAiApiKey: "",
  googleClientId: "",
  sessionSecret: "",
  geminiApiKey: "",
  geminiModel: "gemini-2.5-flash",
  braveApiKey: "",
  tavilyApiKey: "",
};
